module.exports = {
  allowedLicenses: [
    "0BSD",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BlueOak-1.0.0",
    "CC-BY-3.0",
    "CC-BY-4.0",
    "CC0-1.0",
    "ISC",
    "MIT",
    "MPL-2.0",
    "Python-2.0",
    "Unlicense",
    "WTFPL",
    "Zlib",
    "(Apache-2.0 OR MPL-1.1)",
    "(MIT OR Apache-2.0)",
    "(MIT OR CC0-1.0)",
  ],
  ignoredPackages: [],
  package: "./package.json",
  checkDevDependencies: true,
};
