server {
    listen 8080;
    server_name localhost;

    root /app/docs/.vitepress/dist;
    index index.html;

    location / {
        auth_basic "Restricted Access";
        auth_basic_user_file /etc/nginx/.htpasswd;

        try_files $uri $uri.html $uri/ =404;
    }
}
