name: 🔍 CI

on:
  pull_request:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: 🔍 Verify
    runs-on: ubuntu-latest
    steps:
      - name: 🔀 Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: 🔧 Setup pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          HUSKY: "0"

      - name: ⚖️ Licence check
        run: pnpm licence-check

      - name: 📝 Validate commit messages
        uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed # v6

      - name: 🎨 Format check
        run: pnpm format:check

      - name: 📏 Lint
        run: pnpm lint

      - name: 🔍 Typecheck
        run: pnpm typecheck

      - name: 🏗️ Build
        run: pnpm build
